import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const root = process.cwd();
const sourceRoot = path.join(root, 'quazer_pics');
const outputRoot = path.join(root, 'public', 'portfolio');
const directRoot = path.join(root, 'public', 'direct');
const generatedDataFile = path.join(root, 'src', 'data', 'generatedImages.js');
const imageExtensions = /\.(jpe?g|jepg|png|webp|avif|gif|svg|tiff?|bmp|heic|heif)$/i;

const sourceFolders = await fs.readdir(sourceRoot, { withFileTypes: true });
const directories = sourceFolders.filter((entry) => entry.isDirectory()).map((entry) => entry.name);

const renderFolders = findFolders(/render|design/i, [
  'project_madurai_client',
  'project_kasturi_garden',
]);
const carouselFolders = findFolders(/corou?sal|carousel/i, []);
const finishedFolders = findFolders(/finished|complete|completed/i, [
  'Finished_project_dreamHouse',
]);
const logoFolder = directories.find((folder) => /logo/i.test(folder));

await fs.mkdir(outputRoot, { recursive: true });

const renderImages = [
  ...(await processGallery(renderFolders, 'render', 'render', 'Design Render')),
  ...(await processManualPortfolioAssets('render', 'render', 'Design Render')),
  ...(await processDirectAssets(['render', 'our-design'], 'Design Render')),
];
const carouselImages = [
  ...(await processGallery(carouselFolders, 'carousel', 'carousel', 'Carousel Render')),
  ...(await processManualPortfolioAssets('carousel', 'carousel', 'Carousel Render')),
  ...(await processDirectAssets(['carousel'], 'Carousel Render')),
];
const finishedImages = [
  ...(await processGallery(finishedFolders, 'finished', 'finished', 'Finished Project')),
  ...(await processManualPortfolioAssets('finished', 'finished', 'Finished Project')),
  ...(await processDirectAssets(['finished', 'finished-project'], 'Finished Project')),
];
const planImages = [
  ...(await processManualPortfolioAssets('2D plan', '2d-plan', '2D Plan')),
  ...(await processDirectAssets(['2D plan', '2d-plan'], '2D Plan')),
];
const innovationImages = [
  ...(await processManualPortfolioAssets('innovation', 'innovation', 'Innovation', { includeSubdirectories: true })),
  ...(await processDirectAssets(['innovation'], 'Innovation')),
];
const logoAsset = await processLogo(logoFolder);

await fs.writeFile(
  generatedDataFile,
  [
    '// Generated by scripts/prepare-assets.mjs. Do not edit manually.',
    `export const logoAsset = ${JSON.stringify(logoAsset)};`,
    `export const carouselImages = ${JSON.stringify(carouselImages, null, 2)};`,
    `export const renderImages = ${JSON.stringify(renderImages, null, 2)};`,
    `export const finishedImages = ${JSON.stringify(finishedImages, null, 2)};`,
    `export const planImages = ${JSON.stringify(planImages, null, 2)};`,
    `export const innovationImages = ${JSON.stringify(innovationImages, null, 2)};`,
    '',
  ].join('\n'),
);

function findFolders(pattern, fallback) {
  const matched = directories.filter((folder) => pattern.test(folder));
  return matched.length ? matched : fallback.filter((folder) => directories.includes(folder));
}

async function processGallery(folders, outputFolder, prefix, type) {
  const assets = [];
  const folderOutputRoot = path.join(outputRoot, outputFolder);
  await fs.mkdir(folderOutputRoot, { recursive: true });
  await removeGeneratedFiles(folderOutputRoot, prefix);

  for (const folder of folders) {
    const dir = path.join(sourceRoot, folder);
    const files = (await fs.readdir(dir))
      .filter((file) => imageExtensions.test(file) && !/logo/i.test(file))
      .sort();

    for (const file of files) {
      const index = String(assets.length + 1).padStart(2, '0');
      const outputName = `${prefix}-${index}.webp`;
      const source = path.join(dir, file);
      const output = path.join(folderOutputRoot, outputName);

      await sharp(source)
        .rotate()
        .resize({ width: 1800, withoutEnlargement: true })
        .webp({ quality: 78, effort: 5 })
        .toFile(output);

      assets.push({
        src: `/portfolio/${outputFolder}/${outputName}`,
        type,
        project: titleFromFolder(folder),
      });
    }
  }

  return assets;
}

async function removeGeneratedFiles(folder, prefix) {
  const exists = await fs.stat(folder).then((stats) => stats.isDirectory()).catch(() => false);
  if (!exists) return;

  const generatedPattern = new RegExp(`^${prefix}-\\d+\\.webp$`, 'i');
  const files = await fs.readdir(folder);
  await Promise.all(
    files
      .filter((file) => generatedPattern.test(file))
      .map((file) => fs.rm(path.join(folder, file), { force: true })),
  );
}

async function processLogo(folder) {
  const searchFolders = [folder, ...directories].filter(Boolean);

  for (const currentFolder of searchFolders) {
    const dir = path.join(sourceRoot, currentFolder);
    const files = (await fs.readdir(dir))
      .filter((file) => imageExtensions.test(file))
      .filter((file) => currentFolder === folder || /logo/i.test(file));
    const file = files[0];

    if (!file) continue;

    const source = path.join(dir, file);
    const outputName = file.endsWith('.svg') ? 'logo.svg' : 'logo.webp';
    const logoOutputRoot = path.join(outputRoot, 'logo');
    const output = path.join(logoOutputRoot, outputName);
    await fs.mkdir(logoOutputRoot, { recursive: true });

    if (file.endsWith('.svg')) {
      await fs.copyFile(source, output);
    } else {
      await sharp(source).resize({ width: 360, withoutEnlargement: true }).webp({ quality: 84 }).toFile(output);
    }

    return `/portfolio/logo/${outputName}`;
  }

  return '';
}

async function processDirectAssets(folders, type) {
  const assets = [];

  for (const folder of folders) {
    const dir = path.join(directRoot, folder);
    const exists = await fs.stat(dir).then((stats) => stats.isDirectory()).catch(() => false);

    if (!exists) continue;

    const files = (await fs.readdir(dir))
      .filter((file) => imageExtensions.test(file))
      .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

    assets.push(...files.map((file) => ({
      src: `/direct/${folder}/${encodeURIComponent(file)}`,
      type,
      project: titleFromFolder(path.parse(file).name),
    })));
  }

  return assets;
}

async function processManualPortfolioAssets(folder, prefix, type, options = {}) {
  const dir = path.join(outputRoot, folder);
  if (folder === '2D plan') await fs.mkdir(dir, { recursive: true });
  const exists = await fs.stat(dir).then((stats) => stats.isDirectory()).catch(() => false);
  if (!exists) return [];

  const generatedPattern = new RegExp(`^${prefix}-\\d+\\.webp$`, 'i');
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const rootFiles = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name);

  const assets = rootFiles
    .filter((file) => imageExtensions.test(file))
    .filter((file) => !generatedPattern.test(file))
    .map((file) => ({
      src: portfolioAssetPath(folder, file),
      type,
      project: titleFromFolder(path.parse(file).name),
      group: '',
    }));

  if (options.includeSubdirectories) {
    const subfolders = entries
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

    for (const subfolder of subfolders) {
      const subfolderPath = path.join(dir, subfolder);
      const files = (await fs.readdir(subfolderPath))
        .filter((file) => imageExtensions.test(file))
        .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

      assets.push(...files.map((file) => ({
        src: portfolioAssetPath(folder, subfolder, file),
        type,
        project: titleFromFolder(path.parse(file).name),
        group: titleFromFolder(subfolder),
      })));
    }
  }

  return assets.sort((a, b) => a.src.localeCompare(b.src, undefined, { numeric: true, sensitivity: 'base' }));
}

function portfolioAssetPath(...segments) {
  return `/portfolio/${segments.map((segment) => encodeURIComponent(segment)).join('/')}`;
}

function titleFromFolder(folder) {
  return folder
    .replace(/^project_/i, '')
    .replace(/^finished_project_/i, '')
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}
